eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

spring:
  zipkin:
    base-url: http://zipkin:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"
