eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411/
    #base-url: http://localhost:9411/
  redis:
    host: redis
    port: 6379
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
        enabled: false
    loadbalancer:
      ribbon:
        enabled: true
        mode: service

management:
  endpoints:
    web:
      exposure:
        include: "*"
