eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://discovery-server:8761/eureka/
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
#    base-url: http://zipkin:9411/
    base-url: http://localhost:9411/
  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"
