eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discUser:discPassword@discovery-server:8761/eureka/

spring:
  zipkin:
    base-url: http://zipkin:9411/
    #base-url: http://localhost:9411/
  redis:
    host: redis
    port: 6379
  cloud:
    loadbalancer:
      ribbon:
        enabled: false 

management:
  endpoints:
    web:
      exposure:
        include: "*"
