eureka:
  client:
    prefer-ip-address: true
    register-with-eureka: true
    enabled: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411/
