server:
  port: 7979
  
spring:
  rabbitmq:
    host: rabbitmq
    port: 61613
    username: guest
    password: guest
  data:
    mongodb:
      host: mongodb
      authentication-database: admin
      port: 27017
      username: root
      password: root
      database: test
