server:
  port: 9191
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: Ogun2572
    key-store-type: PKCS12
    key-alias: tomcat
  
logging:
  level:
    root: debug
    org:
      springframework:
        web: debug
 
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      default-filters:
      - CircuitBreaker=backendA
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId+':'+getPort()"
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: http://customer-service:9000
          predicates:
            - Path=/customer/**
         # filters:
         #   - CircuitBreaker=backendA
        - id: item-service
          uri: http://item-service:9001
          predicates:
            - Path=/items/** , /storage/**
        - id: order-service
          uri: http://order-service:9002
          predicates:
            - Path=/order/**
        - id: auth-server
          uri: http://auth-server:9898
          predicates:
            - Path=/auth/**, /login
        #- id: storage-service
        #  uri: http://storage-service:9696
        #  predicates:
        #    - Path=/storage/**
        - id: item-details-service
          uri: http://item-details-service:9393
          predicates:
            - Path=/itemDetails/**
        - id: chat-server
          uri: http://chat-server:7979
          predicates:
            - Path=/mywebsockets/**



resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 3s
      failureRateThreshold: 5
      eventConsumerBufferSize: 10
      slowCallDurationThreshold: 9000ms
      slowCallRateThreshold: 30
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalStateException
  instances:
    backendA:
      baseConfig: default
      
resilience4j.timelimiter:
  time-limiter-aspect-order: 398
  configs:
    default:
      timeoutDuration: 10000
      cancelRunningFuture: false
  instances:
    backendA:
      baseConfig: default
