server:
  port: 9191

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**
          filters:
            - CircuitBreaker=backendA 
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 5
      minimumNumberOfCalls: 3
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 10s
      failureRateThreshold: 3
      eventConsumerBufferSize: 10
      slowCallDurationThreshold: 200ms
      slowCallRateThreshold: 30
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalStateException
  instances:
    backendA:
      baseConfig: default
      
