server:
  port: 9191
 
logging:
  level:
    root: debug
    org:
      springframework:
        web: debug

spring:
  cloud:
    kubernetes:
      loadbalancer:
        mode: SERVICE
    gateway:
      default-filters:
      - CircuitBreaker=backendA 
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 3s
      failureRateThreshold: 5
      eventConsumerBufferSize: 10
      slowCallDurationThreshold: 9000ms
      slowCallRateThreshold: 30
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalStateException
  instances:
    backendA:
      baseConfig: default
      
resilience4j.timelimiter:
  time-limiter-aspect-order: 398
  configs:
    default:
      timeoutDuration: 10000
      cancelRunningFuture: false
  instances:
    backendA:
      baseConfig: default
