server:
  port: 9191

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
            - CircuitBreaker=backendA
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**
          filters:
            - CircuitBreaker=backendA
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - CircuitBreaker=backendA
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**, /login
          filters:
            - CircuitBreaker=backendA
        - id: storage-service
          uri: lb://storage-service
          predicates:
            - Path=/storage/**
          filters:
            - CircuitBreaker=backendA
        - id: item-details-service
          uri: lb://item-details-service
          predicates:
            - Path=/itemDetails/**
          filters:
            - CircuitBreaker=backendA



resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 5
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 3s
      failureRateThreshold: 5
      eventConsumerBufferSize: 10
      slowCallDurationThreshold: 200ms
      slowCallRateThreshold: 30
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalStateException
  instances:
    backendA:
      baseConfig: default
      
resilience4j.timelimiter:
  time-limiter-aspect-order: 398
  configs:
    default:
      timeoutDuration: 5s
      cancelRunningFuture: false
  instances:
    backendA:
      baseConfig: default
