server:
  port: 9798

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: ecebf1aecea90b
    password: 62d122ac336b25
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        orderinput:
          destination: ordertoemail
        signininput:
          destination: newsigninalert
        passwordresetinput:
          destination: passwordresetmail
