server:
  port: 9798

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 3cb777c4460e88
    password: 3d6dbc1f5f3548
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        orderinput:
          destination: ordertoemail
        signininput:
          destination: newsigninalert
        passwordresetinput:
          destination: passwordresetmail
