server:
  port: 9798

spring:
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: f080079709d23c
    password: faf1bbd5b17dff
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rajesh
    password: rajesh
  cloud:
    stream:
      bindings:
        orderinput:
          destination: ordertoemail
        signininput:
          destination: newsigninalert
        passwordresetinput:
          destination: passwordresetmail
