server.port: 9001

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: test
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:mysqldb}:3306/itemservice #jdbc:mysql://${MYSQL_HOST:localhost}:3307/authserver
    username: ogn
    password: ogn
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input_file_created:
          destination: itemsavedfilelocation
        input_file_deleted:
          destination: itemdeletedfilelocation
    kubernetes:
      discovery:
        service-name: gateway
        primary-port-name: 9001
        enabled: true
        all-namespaces: true

