server.port: 9001

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: test
  datasource:
    url: jdbc:postgresql://localhost:5432/itemservice #jdbc:mysql://${MYSQL_HOST:localhost}:3307/authserver
    username: postgres
    password: raje1409
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: rajesh
    password: rajesh
  cloud:
    stream:
      bindings:
        input_file_created:
          destination: itemsavedfilelocation
        input_file_deleted:
          destination: itemdeletedfilelocation
        output_item_deleted_for_details:
          destination: deleteitemdetails
        output_item_deleted_for_pictures:
          destination: deleteitempictures
    kubernetes:
      discovery:
        service-name: gateway
        primary-port-name: 9001
        enabled: true
        all-namespaces: true
        
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

