spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: "user"  
    password: "User098"
  cloud:
    stream:
      bindings:
        orderToMailChannel:
          destination: orderToMail
    default:
      contentType: application/json
