spring:
  rabbitmq:
    host: rabbit1
    port: 5672
    username: rabbitmq
    password: rabbitmq
  cloud:
    stream:
      bindings:
        orderToMailChannel:
          destination: orderToMail
    default:
      contentType: application/json
