spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user  
    password: user
  cloud:
    stream:
      bindings:
        orderToMailChannel:
          destination: orderToMail
    default:
      contentType: application/json
