server:
  port: 9696

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    authentication-database: admin
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output_file_created_location:
          destination: itemsavedfilelocation
        output_file_deleted_location:
          destination: itemdeletedfilelocation
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
