server:
  port: 9696

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output_file_created_location:
          destination: itemsavedfilelocation
        output_file_deleted_location:
          destination: itemdeletedfilelocation
