server:
  port: 9696
  
logging:
  level:
    root: debug
    org:
      springframework:
        web: debug


spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output_file_created_location:
          destination: itemsavedfilelocation
        output_file_deleted_location:
          destination: itemdeletedfilelocation
        input_item_deleted_file_location:
          destination: deleteitempictures
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
